version: '3'

services:

  db:
    build: ./db
    restart: always
    environment:
      POSTGRES_PASSWORD: artiz
      POSTGRES_USER: artiz
      POSTGRES_DB: artiz
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  back:
    build: ./back
    ports:
     - "8081:3000"
    volumes:
      - ./back:/usr/src/app/
    depends_on:
      - db

  front:
    build: ./front
    ports:
     - "8082:4200"
     - "49153:49153"
    volumes:
      - ./front/src:/usr/src/app/src
    depends_on:
     - back
  #
  # cypress:
  #   build: ./cypress
  #   depends_on:
  #     - artiz-client
  #   network_mode: "service:artiz-client"
